### ISSUE TITLE
xmlformatter removes attributes with empty value

### ISSUE THREAD

**Issue by the-gigi** [pamoller/xmlformatter#1]
Hi,
Thanks for writing this package. I ran xmlformatter the other day on some XML and it removed an attribute with empty value. This caused a serious problem later because some other code expected the attribute to be there and crashed when it wasn't. The existence of an attribute is part of the information in an XML document. A formatter should not decide to remove them. Here is a distilled example of the issue:

In [7]: xml = '<x a="" />'

In [8]: formatter = xmlformatter.Formatter(indent="2",
   ...:                                    indent_char=" ",
   ...:                                    encoding_output="ISO-8859-1",
   ...:                                    preserve=["literal"])

In [9]: formatter.format_string(xml)
Out[9]: '<x></x>'

**Comment by pamoller** [comment]
Hi,

Sorry I found your notification today. Of course the existence of an empty attribute node may important for a XML application. My intention was to remove unused emptyness from XML documents. So far my programm is simple. It does not respect any XML-schemes. Otherwise, I guess, it would be more error prone. Please take care to vailidate your XML documents by every step of operation.

But thank you. I have changed the formatting rules on GitHub. Now it should behave as you expect.

**Comment by hartwork** [comment]
I believe this issue can be closed as fixed by commit e0e903236c71acaf387bd5f101e8ec0293bdd914 .

**Comment by pamoller** [comment]
solved with 0.2.7
